# 工作流名称
name: Docker

on:
  #schedule:
  #  - cron: '30 19 * * *' # 调度器
  push: # 推送的时候触发
    branches: [ "main" ] # 推送的分支
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  # 仓库地址
  REGISTRY: registry.cn-hangzhou.aliyuncs.com
  # github.repository as <account>/<repo>
  IMAGE_NAME: zrng/myexample # 配置的写法 ${{ github.repository }}
  IMAGE_TAG: Test


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      # 将远程仓库中的源代码领取到workfile自动化构建脚本运行的服务器
      - name: Checkout repository
        uses: actions/checkout@v3 

      # # 安装辅助工具，pr除外
      # # https://github.com/sigstore/cosign-installer
      # - name: Install cosign
      #   if: github.event_name != 'pull_request'
      #   uses: sigstore/cosign-installer@f3c664df7af409cb4873aa5068053ba9d61a57b6 #v2.6.0
      #   with:
      #     cosign-release: 'v1.11.0'

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: login to ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c # 用于登录docker以便我们后续上传镜像到自己的镜像仓库
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.USERMAME }} # 镜像仓库用户名
          password: ${{ secrets.PASSWORD }} # 镜像仓库密码

      # # 为Docker提取元数据
      # # https://github.com/docker/metadata-action
      # - name: Extract Docker metadata
      #   id: meta
      #   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      #   with:
      #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # 生成和推送镜像
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push # 构建docker镜像，推送到自己的docker镜像仓库
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.USERMAME }} # 镜像仓库用户名
          password: ${{ secrets.PASSWORD }} # 镜像仓库密码
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}.${{ github.run_id }}.${{ github.run_number }} #动态变量镜像TAG 使用github运行job和jobid设置tag
          context: . # 相对以远程仓库根路径的dockerfile的路径
          file: ./NetByDocker/Dockerfile # /home/runner/work/my-example/NetByDocker/Dockerfile # 指定Dockerfile

      # 列出所有镜像    
      - name: Docker Images Lst 
        run: docker images
