name: 推送微信消息工作流

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: 推送消息
      run: curl --location --request POST 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=12245545' --header 'Content-Type: application/json' --header 'Accept: */*' --header 'Cache-Control: no-cache' --header 'Host: qyapi.weixin.qq.com' --header 'Connection: keep-alive' --data-raw '{"msgtype":"text","text":{"content":"测试"}}'
